### ISSUE TITLE
How would you run this in Spark 2.3.0?

### ISSUE THREAD

**Issue by netzerk** [atais/Fixed-Length#14]
Hi atais
I found your answer here:
https://stackoverflow.com/questions/38773664/how-to-read-a-fixed-length-file-in-spark-using-dataframe-api-and-scala/45055001#45055001

Only the code example seems to match older Spark versions. it will not compile with Spark 2.3.0.
for this code snippet:
    val fixedWidth = spark.read.text(fileName)
              // .filter(_.trim.nonEmpty)
               .map(Parser.decode[Note])
               .flatMap {
                  case Right(x) => Some(x)
                  case Left(e) =>
                         System.err.println(s"Failed to process file $fileName, error: $e")
                         None
               }
compiler complains:
"...error: type mismatch;
[INFO]  found   : String => Either[Throwable,main.Note]
[INFO]  required: org.apache.spark.sql.Row => ?
[INFO]                .map(Parser.decode[Note])
[INFO]                                  ^
..."
Will you please show an example for calling your API in Spark 2.3.0?
Thanks!

**Comment by atais** [comment]
Spark version does not matter.
Read your compilation error

**Comment by netzerk** [comment]
my bad for replacing the sparkContext from your example with sparkSession, and thank you for the quick answer.
however, now i'm getting this error, which I hope you can guide me through:

error: could not find implicit value for parameter gen: shapeless.Generic.Aux[main.Note,shapeless.::[String,shapeless.::[String,shapeless.::[
...
[Boolean,shapeless.HNil]]]]]]]]]]]
   }.as[Note]

**Comment by atais** [comment]
you have some missing implicit regarding your case class decoding/encoding

**Comment by netzerk** [comment]
I appreciate your support. 
I wish you had a more extensive readme documentation 
at least I got the compilation right at last.
while running I get this error:

18/12/11 08:52:50 WARN TaskSetManager: Lost task 0.0 in stage 5.0 (TID 5, bldd224.bhdc.att.com, executor 2): java.lang.NoSuchMethodError: scala.                                                            Product.$init$(Lscala/Product;)V
        at com.github.atais.fixedlength.Alignment$Left$.<init>(Alignment.scala:8)
        at com.github.atais.fixedlength.Alignment$Left$.<clinit>(Alignment.scala)
        at com.github.atais.fixedlength.Codec$.fixed$default$3(Codec.scala:10)
        at main.Note$.<init>(Note.scala:18)

advice?
thanks

**Comment by atais** [comment]
You can find quite extensive examples in the tests as described in the Readme. Other than that this lib is not much different from circe or any other Scala parsing lib based on shapeless.

About the error tbh I have no idea. Maybe if you could post your code it would be easier.
Or if you find it hard to integrate with spark, firstly adapt my tests to your case scenario with some sample data locally and then just plug it in to spark solution

**Comment by atais** [comment]
There is no spark integration actually done on my side here. It just can be used with spark as it is
